//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandingForm
    {
        public int Id { get; set; }
        public string Full_Name { get; set; }
        public string eMailAddress { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string PostCode { get; set; }
        public string Message { get; set; }
        public Nullable<int> UCRMId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<float> lat { get; set; }
        public Nullable<float> lng { get; set; }
    }
}
