//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class na
    {
        public int id { get; set; }
        public string nasname { get; set; }
        public string shortname { get; set; }
        public string type { get; set; }
        public Nullable<int> ports { get; set; }
        public string secret { get; set; }
        public string server { get; set; }
        public string community { get; set; }
        public string description { get; set; }
    }
}
