//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFCOM
    {
        public int Id { get; set; }
        public string House_no { get; set; }
        public string sitePostcode { get; set; }
        public string C2lettergridsquare { get; set; }
        public string C3lettereasting { get; set; }
        public string C3letternorthing { get; set; }
        public string easting { get; set; }
        public string northing { get; set; }
        public string terminaltype { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string address { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string postcode { get; set; }
    }
}
