//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrionAdminEntities : DbContext
    {
        public OrionAdminEntities()
            : base("name=OrionAdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LandingForm> LandingForms { get; set; }
        public virtual DbSet<radUsagePivot6mth> radUsagePivot6mth { get; set; }
        public virtual DbSet<ReqLog> ReqLogs { get; set; }
        public virtual DbSet<snmpResult> snmpResults { get; set; }
        public virtual DbSet<WebHookLog> WebHookLogs { get; set; }
        public virtual DbSet<snmpResultsEdited> snmpResultsEditeds { get; set; }
        public virtual DbSet<snmpentries6mth> snmpentries6mth { get; set; }
        public virtual DbSet<pppoetoClient> pppoetoClients { get; set; }
        public virtual DbSet<radiusUsage> radiusUsages { get; set; }
        public virtual DbSet<unms_Suspend> unms_Suspend { get; set; }
        public virtual DbSet<OFFCOM> OFFCOMs { get; set; }
    }
}
