//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pppoetoClient
    {
        public int Id { get; set; }
        public string eMail { get; set; }
        public string ClientName { get; set; }
        public string pppoeName { get; set; }
    }
}
