//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class radiusEntities : DbContext
    {
        public radiusEntities()
            : base("name=radiusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<na> nas { get; set; }
        public virtual DbSet<radacct> radaccts { get; set; }
        public virtual DbSet<radcheck> radchecks { get; set; }
        public virtual DbSet<radusergroup> radusergroups { get; set; }
        public virtual DbSet<RadiusEntry> RadiusEntries { get; set; }
    }
}
