//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class radUsagePivot6mth
    {
        public int Id { get; set; }
        public string unms_user { get; set; }
        public string rad_user { get; set; }
        public Nullable<int> C01 { get; set; }
        public Nullable<int> C02 { get; set; }
        public Nullable<int> C03 { get; set; }
        public Nullable<int> C04 { get; set; }
        public Nullable<int> C05 { get; set; }
        public Nullable<int> C06 { get; set; }
        public string Direction { get; set; }
    }
}
