//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebHookLog
    {
        public int Id { get; set; }
        public string body { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
