/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class ClientSummary : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? id;
        private string firstName;
        private string lastName;
        private string companyName;
        private double? balance;
        private string currencyCode;
        private List<Models.ClientServiceSummary> activeServices;
        private List<Models.ClientInvoiceSummary> overdueInvoices;
        private bool? hasOverdueInvoice;
        private bool? hasSuspendedService;
        private bool? hasOutage;
        private bool? isLead;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public double? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("firstName")]
        public string FirstName 
        { 
            get 
            {
                return this.firstName; 
            } 
            set 
            {
                this.firstName = value;
                onPropertyChanged("FirstName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("lastName")]
        public string LastName 
        { 
            get 
            {
                return this.lastName; 
            } 
            set 
            {
                this.lastName = value;
                onPropertyChanged("LastName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("companyName")]
        public string CompanyName 
        { 
            get 
            {
                return this.companyName; 
            } 
            set 
            {
                this.companyName = value;
                onPropertyChanged("CompanyName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("balance")]
        public double? Balance 
        { 
            get 
            {
                return this.balance; 
            } 
            set 
            {
                this.balance = value;
                onPropertyChanged("Balance");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("currencyCode")]
        public string CurrencyCode 
        { 
            get 
            {
                return this.currencyCode; 
            } 
            set 
            {
                this.currencyCode = value;
                onPropertyChanged("CurrencyCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("activeServices")]
        public List<Models.ClientServiceSummary> ActiveServices 
        { 
            get 
            {
                return this.activeServices; 
            } 
            set 
            {
                this.activeServices = value;
                onPropertyChanged("ActiveServices");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("overdueInvoices")]
        public List<Models.ClientInvoiceSummary> OverdueInvoices 
        { 
            get 
            {
                return this.overdueInvoices; 
            } 
            set 
            {
                this.overdueInvoices = value;
                onPropertyChanged("OverdueInvoices");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("hasOverdueInvoice")]
        public bool? HasOverdueInvoice 
        { 
            get 
            {
                return this.hasOverdueInvoice; 
            } 
            set 
            {
                this.hasOverdueInvoice = value;
                onPropertyChanged("HasOverdueInvoice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("hasSuspendedService")]
        public bool? HasSuspendedService 
        { 
            get 
            {
                return this.hasSuspendedService; 
            } 
            set 
            {
                this.hasSuspendedService = value;
                onPropertyChanged("HasSuspendedService");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("hasOutage")]
        public bool? HasOutage 
        { 
            get 
            {
                return this.hasOutage; 
            } 
            set 
            {
                this.hasOutage = value;
                onPropertyChanged("HasOutage");
            }
        }

        /// <summary>
        /// if true, this is a lead, otherwise active client
        /// </summary>
        [JsonProperty("isLead")]
        public bool? IsLead 
        { 
            get 
            {
                return this.isLead; 
            } 
            set 
            {
                this.isLead = value;
                onPropertyChanged("IsLead");
            }
        }
    }
} 