/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class ClientActivity : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.TypeEnum? type;
        private double? id;
        private string createdDate;
        private string dueDate;
        private double? amount;
        private string currencyCode;
        private string invoiceStatus;
        private string paymentMethod;
        private Models.RefundMethodEnum? refundMethod;
        private string invoiceNumber;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("type")]
        public Models.TypeEnum? Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public double? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format
        /// </summary>
        [JsonProperty("createdDate")]
        public string CreatedDate 
        { 
            get 
            {
                return this.createdDate; 
            } 
            set 
            {
                this.createdDate = value;
                onPropertyChanged("CreatedDate");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format
        /// </summary>
        [JsonProperty("dueDate")]
        public string DueDate 
        { 
            get 
            {
                return this.dueDate; 
            } 
            set 
            {
                this.dueDate = value;
                onPropertyChanged("DueDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("amount")]
        public double? Amount 
        { 
            get 
            {
                return this.amount; 
            } 
            set 
            {
                this.amount = value;
                onPropertyChanged("Amount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("currencyCode")]
        public string CurrencyCode 
        { 
            get 
            {
                return this.currencyCode; 
            } 
            set 
            {
                this.currencyCode = value;
                onPropertyChanged("CurrencyCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("invoiceStatus")]
        public string InvoiceStatus 
        { 
            get 
            {
                return this.invoiceStatus; 
            } 
            set 
            {
                this.invoiceStatus = value;
                onPropertyChanged("InvoiceStatus");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("paymentMethod")]
        public string PaymentMethod 
        { 
            get 
            {
                return this.paymentMethod; 
            } 
            set 
            {
                this.paymentMethod = value;
                onPropertyChanged("PaymentMethod");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("refundMethod")]
        public Models.RefundMethodEnum? RefundMethod 
        { 
            get 
            {
                return this.refundMethod; 
            } 
            set 
            {
                this.refundMethod = value;
                onPropertyChanged("RefundMethod");
            }
        }

        /// <summary>
        /// Returns string type if activity is related to invoice otherwise null
        /// </summary>
        [JsonProperty("invoiceNumber")]
        public string InvoiceNumber 
        { 
            get 
            {
                return this.invoiceNumber; 
            } 
            set 
            {
                this.invoiceNumber = value;
                onPropertyChanged("InvoiceNumber");
            }
        }
    }
} 