/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class ClientContactWritable : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<Models.ContactType> types;
        private string email;
        private string phone;
        private string name;
        private bool? isBilling;
        private bool? isContact;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("types")]
        public List<Models.ContactType> Types 
        { 
            get 
            {
                return this.types; 
            } 
            set 
            {
                this.types = value;
                onPropertyChanged("Types");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("email")]
        public string Email 
        { 
            get 
            {
                return this.email; 
            } 
            set 
            {
                this.email = value;
                onPropertyChanged("Email");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("phone")]
        public string Phone 
        { 
            get 
            {
                return this.phone; 
            } 
            set 
            {
                this.phone = value;
                onPropertyChanged("Phone");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Contact is used for Billing notifications
        /// </summary>
        [JsonProperty("isBilling")]
        public bool? IsBilling 
        { 
            get 
            {
                return this.isBilling; 
            } 
            set 
            {
                this.isBilling = value;
                onPropertyChanged("IsBilling");
            }
        }

        /// <summary>
        /// Contact is used for other notifications
        /// </summary>
        [JsonProperty("isContact")]
        public bool? IsContact 
        { 
            get 
            {
                return this.isContact; 
            } 
            set 
            {
                this.isContact = value;
                onPropertyChanged("IsContact");
            }
        }
    }
} 