/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class ClientsStatusCounts : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? withOverdueInvoice;
        private double? withOutage;
        private double? withSuspendedService;
        private double? clientLeads;
        private double? totalCount;

        /// <summary>
        /// Count of clients with overdue invoice.
        /// </summary>
        [JsonProperty("withOverdueInvoice")]
        public double? WithOverdueInvoice 
        { 
            get 
            {
                return this.withOverdueInvoice; 
            } 
            set 
            {
                this.withOverdueInvoice = value;
                onPropertyChanged("WithOverdueInvoice");
            }
        }

        /// <summary>
        /// Count of clients with outage of service.
        /// </summary>
        [JsonProperty("withOutage")]
        public double? WithOutage 
        { 
            get 
            {
                return this.withOutage; 
            } 
            set 
            {
                this.withOutage = value;
                onPropertyChanged("WithOutage");
            }
        }

        /// <summary>
        /// Count of clients with suspended service.
        /// </summary>
        [JsonProperty("withSuspendedService")]
        public double? WithSuspendedService 
        { 
            get 
            {
                return this.withSuspendedService; 
            } 
            set 
            {
                this.withSuspendedService = value;
                onPropertyChanged("WithSuspendedService");
            }
        }

        /// <summary>
        /// Count of client leads.
        /// </summary>
        [JsonProperty("clientLeads")]
        public double? ClientLeads 
        { 
            get 
            {
                return this.clientLeads; 
            } 
            set 
            {
                this.clientLeads = value;
                onPropertyChanged("ClientLeads");
            }
        }

        /// <summary>
        /// Count of all clients and leads.
        /// </summary>
        [JsonProperty("totalCount")]
        public double? TotalCount 
        { 
            get 
            {
                return this.totalCount; 
            } 
            set 
            {
                this.totalCount = value;
                onPropertyChanged("TotalCount");
            }
        }
    }
} 