/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;



namespace webapi.Models
{
    public class ClientAttributeReadOnly : BaseModel 
    {
        // These fields hold the values for the public properties.
        public int id { get; set; }
        public int clientId { get; set; }
        public string name { get; set; }
        public string key { get; set; }
        public string value { get; set; }
        public int? customAttributeId { get; set; }


    }
} 