/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;



namespace webapi.Models
{
    public enum ClientTypeEnum
    {
        ENUM_1 = 1, //Residential
        ENUM_2 = 2, //Company
    }

    /// <summary>
    /// Helper for the enum type ClientTypeEnum
    /// </summary>
    public static class ClientTypeEnumHelper
    {
        /// <summary>
        /// Convert a list of ClientTypeEnum values to a list of integers
        /// </summary>
        /// <param name="enumValues">The list of ClientTypeEnum values to convert</param>
        /// <returns>The list of representative integer values</returns>
        public static List<int> ToValue(List<ClientTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;
            
            return enumValues.Select(eVal => (int)eVal).ToList();
        }
    }
} 