/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;



namespace webapi.Models
{
    public enum DiscountTypeEnum
    {
        ENUM_0 = 0, //No discount
        ENUM_1 = 1, //Percentage discount
        ENUM_2 = 2, //Fixed discount
    }

    /// <summary>
    /// Helper for the enum type DiscountTypeEnum
    /// </summary>
    public static class DiscountTypeEnumHelper
    {
        /// <summary>
        /// Convert a list of DiscountTypeEnum values to a list of integers
        /// </summary>
        /// <param name="enumValues">The list of DiscountTypeEnum values to convert</param>
        /// <returns>The list of representative integer values</returns>
        public static List<int> ToValue(List<DiscountTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;
            
            return enumValues.Select(eVal => (int)eVal).ToList();
        }
    }
} 