/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;



namespace webapi.Models
{
    public enum EncryptionTypeEnum
    {
        ENUM_0 = 0, //None
        ENUM_1 = 1, //WEP
        ENUM_2 = 2, //WPA
        ENUM_3 = 3, //WPA2EAP
        ENUM_4 = 4, //WPAEAP
        ENUM_5 = 5, //WPAEAP / WPA2EAP
        ENUM_6 = 6, //WPA2PSK
        ENUM_7 = 7, //WPA2PSK / WPA2EAP
        ENUM_8 = 8, //WPA2PSK / WPAEAP
        ENUM_9 = 9, //WPA2PSK / WPAEAP / WPA2EAP
        ENUM_10 = 10, //WPAPSK
        ENUM_11 = 11, //WPAPSK / WPA2EAP
        ENUM_12 = 12, //WPAPSK / WPAEAP
        ENUM_13 = 13, //WPAPSK / WPAEAP / WPA2EAP
        ENUM_14 = 14, //WPAPSK / WPA2PSK
        ENUM_15 = 15, //WPAPSK / WPA2PSK / WPA2EAP
        ENUM_16 = 16, //WPAPSK / WPA2PSK / WPAEAP
        ENUM_17 = 17, //WPAPSK / WPA2PSK / WPAEAP / WPA2EAP
    }

    /// <summary>
    /// Helper for the enum type EncryptionTypeEnum
    /// </summary>
    public static class EncryptionTypeEnumHelper
    {
        /// <summary>
        /// Convert a list of EncryptionTypeEnum values to a list of integers
        /// </summary>
        /// <param name="enumValues">The list of EncryptionTypeEnum values to convert</param>
        /// <returns>The list of representative integer values</returns>
        public static List<int> ToValue(List<EncryptionTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;
            
            return enumValues.Select(eVal => (int)eVal).ToList();
        }
    }
} 