/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class Errors : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<string> someField;

        /// <summary>
        /// Array of validation errors
        /// </summary>
        [JsonProperty("someField")]
        public List<string> SomeField 
        { 
            get 
            {
                return this.someField; 
            } 
            set 
            {
                this.someField = value;
                onPropertyChanged("SomeField");
            }
        }
    }
} 