/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;



namespace webapi.Models
{
    public enum InvoiceStatusEnum
    {
        ENUM_0 = 0, //Draft
        ENUM_1 = 1, //Unpaid
        ENUM_2 = 2, //Partially paid
        ENUM_3 = 3, //Paid
        ENUM_4 = 4, //Void
        ENUM_5 = 5, //Processed proforma
    }

    /// <summary>
    /// Helper for the enum type InvoiceStatusEnum
    /// </summary>
    public static class InvoiceStatusEnumHelper
    {
        /// <summary>
        /// Convert a list of InvoiceStatusEnum values to a list of integers
        /// </summary>
        /// <param name="enumValues">The list of InvoiceStatusEnum values to convert</param>
        /// <returns>The list of representative integer values</returns>
        public static List<int> ToValue(List<InvoiceStatusEnum> enumValues)
        {
            if (null == enumValues)
                return null;
            
            return enumValues.Select(eVal => (int)eVal).ToList();
        }
    }
} 