/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class InvoiceAttribute : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string mvalue;
        private int? customAttributeId;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("value")]
        public string Value 
        { 
            get 
            {
                return this.mvalue; 
            } 
            set 
            {
                this.mvalue = value;
                onPropertyChanged("Value");
            }
        }

        /// <summary>
        /// See [Retrieve Custom Attributes](#reference/custom-attributes/custom-attributes/get)
        /// </summary>
        [JsonProperty("customAttributeId")]
        public int? CustomAttributeId 
        { 
            get 
            {
                return this.customAttributeId; 
            } 
            set 
            {
                this.customAttributeId = value;
                onPropertyChanged("CustomAttributeId");
            }
        }
    }
} 