/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class InvoicingOverview : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? totalDue;
        private double? totalOverdue;
        private double? invoicedThisMonth;
        private double? invoicedThisMonthUnpaid;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("totalDue")]
        public double? TotalDue 
        { 
            get 
            {
                return this.totalDue; 
            } 
            set 
            {
                this.totalDue = value;
                onPropertyChanged("TotalDue");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("totalOverdue")]
        public double? TotalOverdue 
        { 
            get 
            {
                return this.totalOverdue; 
            } 
            set 
            {
                this.totalOverdue = value;
                onPropertyChanged("TotalOverdue");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("invoicedThisMonth")]
        public double? InvoicedThisMonth 
        { 
            get 
            {
                return this.invoicedThisMonth; 
            } 
            set 
            {
                this.invoicedThisMonth = value;
                onPropertyChanged("InvoicedThisMonth");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("invoicedThisMonthUnpaid")]
        public double? InvoicedThisMonthUnpaid 
        { 
            get 
            {
                return this.invoicedThisMonthUnpaid; 
            } 
            set 
            {
                this.invoicedThisMonthUnpaid = value;
                onPropertyChanged("InvoicedThisMonthUnpaid");
            }
        }
    }
} 