/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class InvoicesStatusCounts : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string status;
        private double? invoicesCount;

        /// <summary>
        /// Invoice status
        /// </summary>
        [JsonProperty("status")]
        public string Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// Count of invoices with this status.
        /// </summary>
        [JsonProperty("invoicesCount")]
        public double? InvoicesCount 
        { 
            get 
            {
                return this.invoicesCount; 
            } 
            set 
            {
                this.invoicesCount = value;
                onPropertyChanged("InvoicesCount");
            }
        }
    }
} 