/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class InvoiceTemplateReadOnly : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? id;
        private string name;
        private string createdDate;
        private bool? isOfficial;
        private bool? isValid;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public double? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format
        /// </summary>
        [JsonProperty("createdDate")]
        public string CreatedDate 
        { 
            get 
            {
                return this.createdDate; 
            } 
            set 
            {
                this.createdDate = value;
                onPropertyChanged("CreatedDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("isOfficial")]
        public bool? IsOfficial 
        { 
            get 
            {
                return this.isOfficial; 
            } 
            set 
            {
                this.isOfficial = value;
                onPropertyChanged("IsOfficial");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("isValid")]
        public bool? IsValid 
        { 
            get 
            {
                return this.isValid; 
            } 
            set 
            {
                this.isValid = value;
                onPropertyChanged("IsValid");
            }
        }
    }
} 