/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;



namespace webapi.Models
{
    public enum InvoicingPeriodTypeEnum
    {
        ENUM_1 = 1, //Backwards - Recurring invoices are created at the end of the billing period
        ENUM_2 = 2, //Forwards - Recurring invoices are created at the beginning of billing period (clients pay for the service in advance)
    }

    /// <summary>
    /// Helper for the enum type InvoicingPeriodTypeEnum
    /// </summary>
    public static class InvoicingPeriodTypeEnumHelper
    {
        /// <summary>
        /// Convert a list of InvoicingPeriodTypeEnum values to a list of integers
        /// </summary>
        /// <param name="enumValues">The list of InvoicingPeriodTypeEnum values to convert</param>
        /// <returns>The list of representative integer values</returns>
        public static List<int> ToValue(List<InvoicingPeriodTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;
            
            return enumValues.Select(eVal => (int)eVal).ToList();
        }
    }
} 