/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class JobAttachment : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double jobId;
        private string filename;

        /// <summary>
        /// See [Retrieve Jobs](#reference/jobs/schedulingjobs/get)
        /// </summary>
        [JsonProperty("jobId")]
        public double JobId 
        { 
            get 
            {
                return this.jobId; 
            } 
            set 
            {
                this.jobId = value;
                onPropertyChanged("JobId");
            }
        }

        /// <summary>
        /// File name
        /// </summary>
        [JsonProperty("filename")]
        public string Filename 
        { 
            get 
            {
                return this.filename; 
            } 
            set 
            {
                this.filename = value;
                onPropertyChanged("Filename");
            }
        }
    }
} 