/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class JobReadOnly : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? id;
        private List<Models.JobAttachmentReadOnly> attachments;
        private List<Models.JobTaskReadOnly> tasks;
        private string title;
        private string description;
        private double? assignedUserId;
        private double? clientId;
        private string date;
        private double? duration;
        private Models.JobStatusEnum? status0;
        private string address;
        private string gpsLat;
        private string gpsLon;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public double? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("attachments")]
        public List<Models.JobAttachmentReadOnly> Attachments 
        { 
            get 
            {
                return this.attachments; 
            } 
            set 
            {
                this.attachments = value;
                onPropertyChanged("Attachments");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("tasks")]
        public List<Models.JobTaskReadOnly> Tasks 
        { 
            get 
            {
                return this.tasks; 
            } 
            set 
            {
                this.tasks = value;
                onPropertyChanged("Tasks");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// See [Retrieve Users](#reference/users/usersadmins/get)
        /// </summary>
        [JsonProperty("assignedUserId")]
        public double? AssignedUserId 
        { 
            get 
            {
                return this.assignedUserId; 
            } 
            set 
            {
                this.assignedUserId = value;
                onPropertyChanged("AssignedUserId");
            }
        }

        /// <summary>
        /// See [Retrieve Clients](#reference/clients/clients/get)
        /// </summary>
        [JsonProperty("clientId")]
        public double? ClientId 
        { 
            get 
            {
                return this.clientId; 
            } 
            set 
            {
                this.clientId = value;
                onPropertyChanged("ClientId");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format
        /// </summary>
        [JsonProperty("date")]
        public string Date 
        { 
            get 
            {
                return this.date; 
            } 
            set 
            {
                this.date = value;
                onPropertyChanged("Date");
            }
        }

        /// <summary>
        /// Duration of job in minutes
        /// </summary>
        [JsonProperty("duration")]
        public double? Duration 
        { 
            get 
            {
                return this.duration; 
            } 
            set 
            {
                this.duration = value;
                onPropertyChanged("Duration");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("status `0`")]
        public Models.JobStatusEnum? Status0 
        { 
            get 
            {
                return this.status0; 
            } 
            set 
            {
                this.status0 = value;
                onPropertyChanged("Status0");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("address")]
        public string Address 
        { 
            get 
            {
                return this.address; 
            } 
            set 
            {
                this.address = value;
                onPropertyChanged("Address");
            }
        }

        /// <summary>
        /// Latitude of location
        /// </summary>
        [JsonProperty("gpsLat")]
        public string GpsLat 
        { 
            get 
            {
                return this.gpsLat; 
            } 
            set 
            {
                this.gpsLat = value;
                onPropertyChanged("GpsLat");
            }
        }

        /// <summary>
        /// Longitude of location
        /// </summary>
        [JsonProperty("gpsLon")]
        public string GpsLon 
        { 
            get 
            {
                return this.gpsLon; 
            } 
            set 
            {
                this.gpsLon = value;
                onPropertyChanged("GpsLon");
            }
        }
    }
} 