/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;



namespace webapi.Models
{
    public enum JobStatusEnum
    {
        ENUM_0 = 0, //Open
        ENUM_1 = 1, //In progress
        ENUM_2 = 2, //Closed
    }

    /// <summary>
    /// Helper for the enum type JobStatusEnum
    /// </summary>
    public static class JobStatusEnumHelper
    {
        /// <summary>
        /// Convert a list of JobStatusEnum values to a list of integers
        /// </summary>
        /// <param name="enumValues">The list of JobStatusEnum values to convert</param>
        /// <returns>The list of representative integer values</returns>
        public static List<int> ToValue(List<JobStatusEnum> enumValues)
        {
            if (null == enumValues)
                return null;
            
            return enumValues.Select(eVal => (int)eVal).ToList();
        }
    }
} 