/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class MobileLoginPOSTResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string authenticationKey;
        private Models.UserReadOnly user;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("authenticationKey")]
        public string AuthenticationKey 
        { 
            get 
            {
                return this.authenticationKey; 
            } 
            set 
            {
                this.authenticationKey = value;
                onPropertyChanged("AuthenticationKey");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("user")]
        public Models.UserReadOnly User 
        { 
            get 
            {
                return this.user; 
            } 
            set 
            {
                this.user = value;
                onPropertyChanged("User");
            }
        }
    }
} 