/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class MobileDashboardOverviewGETResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.Organization1 organization;
        private Models.Overview overview;
        private Models.InvoicingOverview invoicingOverview;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("organization")]
        public Models.Organization1 Organization 
        { 
            get 
            {
                return this.organization; 
            } 
            set 
            {
                this.organization = value;
                onPropertyChanged("Organization");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("overview")]
        public Models.Overview Overview 
        { 
            get 
            {
                return this.overview; 
            } 
            set 
            {
                this.overview = value;
                onPropertyChanged("Overview");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("invoicingOverview")]
        public Models.InvoicingOverview InvoicingOverview 
        { 
            get 
            {
                return this.invoicingOverview; 
            } 
            set 
            {
                this.invoicingOverview = value;
                onPropertyChanged("InvoicingOverview");
            }
        }
    }
} 