/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class MobileDashboardLastWeekTrafficGETResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? downloadTotal;
        private double? uploadTotal;
        private List<Models.TrafficItem> chart;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("downloadTotal")]
        public double? DownloadTotal 
        { 
            get 
            {
                return this.downloadTotal; 
            } 
            set 
            {
                this.downloadTotal = value;
                onPropertyChanged("DownloadTotal");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("uploadTotal")]
        public double? UploadTotal 
        { 
            get 
            {
                return this.uploadTotal; 
            } 
            set 
            {
                this.uploadTotal = value;
                onPropertyChanged("UploadTotal");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("chart")]
        public List<Models.TrafficItem> Chart 
        { 
            get 
            {
                return this.chart; 
            } 
            set 
            {
                this.chart = value;
                onPropertyChanged("Chart");
            }
        }
    }
} 