/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class MobileLoginPOSTRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string user;
        private string password;
        private double? expiration;
        private double? sliding;
        private string deviceName;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("user")]
        public string User 
        { 
            get 
            {
                return this.user; 
            } 
            set 
            {
                this.user = value;
                onPropertyChanged("User");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("password")]
        public string Password 
        { 
            get 
            {
                return this.password; 
            } 
            set 
            {
                this.password = value;
                onPropertyChanged("Password");
            }
        }

        /// <summary>
        /// Expiration time in seconds, max 604800 (7 days).
        /// </summary>
        [JsonProperty("expiration")]
        public double? Expiration 
        { 
            get 
            {
                return this.expiration; 
            } 
            set 
            {
                this.expiration = value;
                onPropertyChanged("Expiration");
            }
        }

        /// <summary>
        /// 1 to prolong expiration each time the key is used, 0 otherwise.
        /// </summary>
        [JsonProperty("sliding")]
        public double? Sliding 
        { 
            get 
            {
                return this.sliding; 
            } 
            set 
            {
                this.sliding = value;
                onPropertyChanged("Sliding");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceName")]
        public string DeviceName 
        { 
            get 
            {
                return this.deviceName; 
            } 
            set 
            {
                this.deviceName = value;
                onPropertyChanged("DeviceName");
            }
        }
    }
} 