/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;



namespace webapi.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum Order4Enum
    {
        CREATEDAT, //TODO: Write general description for this method
        ID, //TODO: Write general description for this method
        LASTACTIVITY, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type Order4Enum
    /// </summary>
    public static class Order4EnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "createdAt", "id", "lastActivity" };

        /// <summary>
        /// Converts a Order4Enum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The Order4Enum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(Order4Enum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case Order4Enum.CREATEDAT:
                case Order4Enum.ID:
                case Order4Enum.LASTACTIVITY:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of Order4Enum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of Order4Enum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<Order4Enum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into Order4Enum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed Order4Enum value</returns>
        public static Order4Enum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type Order4Enum", value));

            return (Order4Enum) index;
        }
    }
} 