/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;



namespace webapi.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum OrderEnum
    {
        ENUM_USERFIRSTNAME, //TODO: Write general description for this method
        ENUM_USERLASTNAME, //TODO: Write general description for this method
        ENUM_CLIENTREGISTRATIONDATE, //TODO: Write general description for this method
        ENUM_CLIENTID, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type OrderEnum
    /// </summary>
    public static class OrderEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "user.firstName", "user.lastName", "client.registrationDate", "client.id" };

        /// <summary>
        /// Converts a OrderEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The OrderEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(OrderEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case OrderEnum.ENUM_USERFIRSTNAME:
                case OrderEnum.ENUM_USERLASTNAME:
                case OrderEnum.ENUM_CLIENTREGISTRATIONDATE:
                case OrderEnum.ENUM_CLIENTID:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of OrderEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of OrderEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<OrderEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into OrderEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed OrderEnum value</returns>
        public static OrderEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type OrderEnum", value));

            return (OrderEnum) index;
        }
    }
} 