/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class Overview : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? clientCount;
        private double? clientLeadCount;
        private double? clientSuspendedCount;
        private double? clientOverdueCount;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("clientCount")]
        public double? ClientCount 
        { 
            get 
            {
                return this.clientCount; 
            } 
            set 
            {
                this.clientCount = value;
                onPropertyChanged("ClientCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("clientLeadCount")]
        public double? ClientLeadCount 
        { 
            get 
            {
                return this.clientLeadCount; 
            } 
            set 
            {
                this.clientLeadCount = value;
                onPropertyChanged("ClientLeadCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("clientSuspendedCount")]
        public double? ClientSuspendedCount 
        { 
            get 
            {
                return this.clientSuspendedCount; 
            } 
            set 
            {
                this.clientSuspendedCount = value;
                onPropertyChanged("ClientSuspendedCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("clientOverdueCount")]
        public double? ClientOverdueCount 
        { 
            get 
            {
                return this.clientOverdueCount; 
            } 
            set 
            {
                this.clientOverdueCount = value;
                onPropertyChanged("ClientOverdueCount");
            }
        }
    }
} 