/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class PaymentAttributeReadOnly : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? id;
        private int paymentId;
        private string name;
        private string key;
        private string mvalue;
        private double? customAttributeId;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public double? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("paymentId")]
        public int InvoiceId 
        { 
            get 
            {
                return this.paymentId; 
            } 
            set 
            {
                this.paymentId = value;
                onPropertyChanged("PaymentId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("key")]
        public string Key 
        { 
            get 
            {
                return this.key; 
            } 
            set 
            {
                this.key = value;
                onPropertyChanged("Key");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("value")]
        public string Value 
        { 
            get 
            {
                return this.mvalue; 
            } 
            set 
            {
                this.mvalue = value;
                onPropertyChanged("Value");
            }
        }

        /// <summary>
        /// See [Retrieve Custom Attributes](#reference/custom-attributes/custom-attributes/get)
        /// </summary>
        [JsonProperty("customAttributeId")]
        public double? CustomAttributeId 
        { 
            get 
            {
                return this.customAttributeId; 
            } 
            set 
            {
                this.customAttributeId = value;
                onPropertyChanged("CustomAttributeId");
            }
        }
    }
} 