/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class PaymentReadOnly : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? id;
        private double? clientId;
        private Models.PaymentMethodEnum method;
        private string checkNumber;
        private string createdDate;
        private double amount;
        private List<Models.PaymentAttributeReadOnly> attributes;
        private string currencyCode;
        private string note;
        private string receiptSentDate;
        private string providerName;
        private string providerPaymentId;
        private string providerPaymentTime;
        private List<Models.PaymentCoverReadOnly> paymentCovers;
        private double? creditAmount;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public double? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("clientId")]
        public double? ClientId 
        { 
            get 
            {
                return this.clientId; 
            } 
            set 
            {
                this.clientId = value;
                onPropertyChanged("ClientId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("method")]
        public Models.PaymentMethodEnum Method 
        { 
            get 
            {
                return this.method; 
            } 
            set 
            {
                this.method = value;
                onPropertyChanged("Method");
            }
        }

        /// <summary>
        /// Applicable in case of **Check** method only
        /// </summary>
        [JsonProperty("checkNumber")]
        public string CheckNumber 
        { 
            get 
            {
                return this.checkNumber; 
            } 
            set 
            {
                this.checkNumber = value;
                onPropertyChanged("CheckNumber");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format. If not specified, current date will be used.
        /// </summary>
        [JsonProperty("createdDate")]
        public string CreatedDate 
        { 
            get 
            {
                return this.createdDate; 
            } 
            set 
            {
                this.createdDate = value;
                onPropertyChanged("CreatedDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("amount")]
        public double Amount 
        { 
            get 
            {
                return this.amount; 
            } 
            set 
            {
                this.amount = value;
                onPropertyChanged("Amount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("currencyCode")]
        public string CurrencyCode 
        { 
            get 
            {
                return this.currencyCode; 
            } 
            set 
            {
                this.currencyCode = value;
                onPropertyChanged("CurrencyCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("note")]
        public string Note 
        { 
            get 
            {
                return this.note; 
            } 
            set 
            {
                this.note = value;
                onPropertyChanged("Note");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format or null if receipt was not sent.
        /// </summary>
        [JsonProperty("receiptSentDate")]
        public string ReceiptSentDate 
        { 
            get 
            {
                return this.receiptSentDate; 
            } 
            set 
            {
                this.receiptSentDate = value;
                onPropertyChanged("ReceiptSentDate");
            }
        }

        /// <summary>
        /// Required in case of **Custom** method.
        /// </summary>
        [JsonProperty("providerName")]
        public string ProviderName 
        { 
            get 
            {
                return this.providerName; 
            } 
            set 
            {
                this.providerName = value;
                onPropertyChanged("ProviderName");
            }
        }

        /// <summary>
        /// Required in case of **Custom** method.
        /// </summary>
        [JsonProperty("providerPaymentId")]
        public string ProviderPaymentId 
        { 
            get 
            {
                return this.providerPaymentId; 
            } 
            set 
            {
                this.providerPaymentId = value;
                onPropertyChanged("ProviderPaymentId");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format. If not specified, current date will be used. Required in case of **Custom** method.
        /// </summary>
        [JsonProperty("providerPaymentTime")]
        public string ProviderPaymentTime 
        { 
            get 
            {
                return this.providerPaymentTime; 
            } 
            set 
            {
                this.providerPaymentTime = value;
                onPropertyChanged("ProviderPaymentTime");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("paymentCovers")]
        public List<Models.PaymentCoverReadOnly> PaymentCovers 
        { 
            get 
            {
                return this.paymentCovers; 
            } 
            set 
            {
                this.paymentCovers = value;
                onPropertyChanged("PaymentCovers");
            }
        }
        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("attributes")]
        public List<Models.PaymentAttributeReadOnly> Attributes
        {
            get
            {
                return this.attributes;
            }
            set
            {
                this.attributes = value;
                onPropertyChanged("Attributes");
            }
        }
        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("creditAmount")]
        public double? CreditAmount 
        { 
            get 
            {
                return this.creditAmount; 
            } 
            set 
            {
                this.creditAmount = value;
                onPropertyChanged("CreditAmount");
            }
        }
    }
} 