/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;



namespace webapi.Models
{
    public enum PolarizationEnum
    {
        ENUM_1 = 1, //Vertical
        ENUM_2 = 2, //Horizontal
        ENUM_3 = 3, //Both
    }

    /// <summary>
    /// Helper for the enum type PolarizationEnum
    /// </summary>
    public static class PolarizationEnumHelper
    {
        /// <summary>
        /// Convert a list of PolarizationEnum values to a list of integers
        /// </summary>
        /// <param name="enumValues">The list of PolarizationEnum values to convert</param>
        /// <returns>The list of representative integer values</returns>
        public static List<int> ToValue(List<PolarizationEnum> enumValues)
        {
            if (null == enumValues)
                return null;
            
            return enumValues.Select(eVal => (int)eVal).ToList();
        }
    }
} 