/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;



namespace webapi.Models
{
    public enum QosEnabledEnum
    {
        ENUM_0 = 0, //No
        ENUM_1 = 1, //On this device
        ENUM_2 = 2, //On other device(s)
    }

    /// <summary>
    /// Helper for the enum type QosEnabledEnum
    /// </summary>
    public static class QosEnabledEnumHelper
    {
        /// <summary>
        /// Convert a list of QosEnabledEnum values to a list of integers
        /// </summary>
        /// <param name="enumValues">The list of QosEnabledEnum values to convert</param>
        /// <returns>The list of representative integer values</returns>
        public static List<int> ToValue(List<QosEnabledEnum> enumValues)
        {
            if (null == enumValues)
                return null;
            
            return enumValues.Select(eVal => (int)eVal).ToList();
        }
    }
} 