/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;



namespace webapi.Models
{
    public enum QuoteStatusEnum
    {
        ENUM_0 = 0, //Open
        ENUM_1 = 1, //Accepted
        ENUM_2 = 2, //Rejected
    }

    /// <summary>
    /// Helper for the enum type QuoteStatusEnum
    /// </summary>
    public static class QuoteStatusEnumHelper
    {
        /// <summary>
        /// Convert a list of QuoteStatusEnum values to a list of integers
        /// </summary>
        /// <param name="enumValues">The list of QuoteStatusEnum values to convert</param>
        /// <returns>The list of representative integer values</returns>
        public static List<int> ToValue(List<QuoteStatusEnum> enumValues)
        {
            if (null == enumValues)
                return null;
            
            return enumValues.Select(eVal => (int)eVal).ToList();
        }
    }
} 