/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class QuoteItem : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string label;
        private double price;
        private double? quantity;
        private string unit;
        private double? tax1Id;
        private double? tax2Id;
        private double? tax3Id;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("label")]
        public string Label 
        { 
            get 
            {
                return this.label; 
            } 
            set 
            {
                this.label = value;
                onPropertyChanged("Label");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("price")]
        public double Price 
        { 
            get 
            {
                return this.price; 
            } 
            set 
            {
                this.price = value;
                onPropertyChanged("Price");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("quantity")]
        public double? Quantity 
        { 
            get 
            {
                return this.quantity; 
            } 
            set 
            {
                this.quantity = value;
                onPropertyChanged("Quantity");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("unit")]
        public string Unit 
        { 
            get 
            {
                return this.unit; 
            } 
            set 
            {
                this.unit = value;
                onPropertyChanged("Unit");
            }
        }

        /// <summary>
        /// See [Retrieve Taxes](#reference/taxes/taxes/get)
        /// </summary>
        [JsonProperty("tax1Id")]
        public double? Tax1Id 
        { 
            get 
            {
                return this.tax1Id; 
            } 
            set 
            {
                this.tax1Id = value;
                onPropertyChanged("Tax1Id");
            }
        }

        /// <summary>
        /// If your pricing mode is set to "Tax inclusive pricing", only single tax can be set.
        /// See [Retrieve Taxes](#reference/taxes/taxes/get)
        /// </summary>
        [JsonProperty("tax2Id")]
        public double? Tax2Id 
        { 
            get 
            {
                return this.tax2Id; 
            } 
            set 
            {
                this.tax2Id = value;
                onPropertyChanged("Tax2Id");
            }
        }

        /// <summary>
        /// If your pricing mode is set to "Tax inclusive pricing", only single tax can be set.
        /// See [Retrieve Taxes](#reference/taxes/taxes/get)
        /// </summary>
        [JsonProperty("tax3Id")]
        public double? Tax3Id 
        { 
            get 
            {
                return this.tax3Id; 
            } 
            set 
            {
                this.tax3Id = value;
                onPropertyChanged("Tax3Id");
            }
        }
    }
} 