/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;



namespace webapi.Models
{
    public enum RefundMethod1Enum
    {
        ENUM_1 = 1, //Check
        ENUM_2 = 2, //Cash
        ENUM_3 = 3, //Bank transfer
        ENUM_4 = 4, //PayPal
        ENUM_5 = 5, //PayPal credit card
        ENUM_6 = 6, //Stripe credit card
        ENUM_7 = 7, //Stripe subscription (credit card)
        ENUM_8 = 8, //PayPal subscription
        ENUM_9 = 9, //Authorize.Net credit card
        ENUM_10 = 10, //Authorize.Net subscription
        ENUM_12 = 12, //IPPay
        ENUM_13 = 13, //IPPay subscription
        ENUM_14 = 14, //MercadoPago
        ENUM_15 = 15, //MercadoPago subscription
        ENUM_16 = 16, //Stripe ACH
        ENUM_17 = 17, //Stripe subscription (ACH)
        ENUM_99 = 99, //Custom
    }

    /// <summary>
    /// Helper for the enum type RefundMethod1Enum
    /// </summary>
    public static class RefundMethod1EnumHelper
    {
        /// <summary>
        /// Convert a list of RefundMethod1Enum values to a list of integers
        /// </summary>
        /// <param name="enumValues">The list of RefundMethod1Enum values to convert</param>
        /// <returns>The list of representative integer values</returns>
        public static List<int> ToValue(List<RefundMethod1Enum> enumValues)
        {
            if (null == enumValues)
                return null;
            
            return enumValues.Select(eVal => (int)eVal).ToList();
        }
    }
} 