/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class ServiceSurchargeReadOnly : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? id;
        private double? serviceId;
        private double? surchargeId;
        private string invoiceLabel;
        private double? price;
        private bool? taxable;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public double? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("serviceId")]
        public double? ServiceId 
        { 
            get 
            {
                return this.serviceId; 
            } 
            set 
            {
                this.serviceId = value;
                onPropertyChanged("ServiceId");
            }
        }

        /// <summary>
        /// See [Retrieve Surcharges](#reference/surcharges/surcharges/get)
        /// </summary>
        [JsonProperty("surchargeId")]
        public double? SurchargeId 
        { 
            get 
            {
                return this.surchargeId; 
            } 
            set 
            {
                this.surchargeId = value;
                onPropertyChanged("SurchargeId");
            }
        }

        /// <summary>
        /// If not specified, surcharge name will be used
        /// </summary>
        [JsonProperty("invoiceLabel")]
        public string InvoiceLabel 
        { 
            get 
            {
                return this.invoiceLabel; 
            } 
            set 
            {
                this.invoiceLabel = value;
                onPropertyChanged("InvoiceLabel");
            }
        }

        /// <summary>
        /// Price per period
        /// </summary>
        [JsonProperty("price")]
        public double? Price 
        { 
            get 
            {
                return this.price; 
            } 
            set 
            {
                this.price = value;
                onPropertyChanged("Price");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("taxable")]
        public bool? Taxable 
        { 
            get 
            {
                return this.taxable; 
            } 
            set 
            {
                this.taxable = value;
                onPropertyChanged("Taxable");
            }
        }
    }
} 