/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;



namespace webapi.Models
{
    public enum ServiceStatusEnum
    {
        ENUM_0 = 0, //Prepared
        ENUM_1 = 1, //Active
        ENUM_2 = 2, //Ended
        ENUM_3 = 3, //Suspended
        ENUM_4 = 4, //Prepared blocked
        ENUM_5 = 5, //Obsolete
        ENUM_6 = 6, //Deferred
        ENUM_7 = 7, //Quoted
    }

    /// <summary>
    /// Helper for the enum type ServiceStatusEnum
    /// </summary>
    public static class ServiceStatusEnumHelper
    {
        /// <summary>
        /// Convert a list of ServiceStatusEnum values to a list of integers
        /// </summary>
        /// <param name="enumValues">The list of ServiceStatusEnum values to convert</param>
        /// <returns>The list of representative integer values</returns>
        public static List<int> ToValue(List<ServiceStatusEnum> enumValues)
        {
            if (null == enumValues)
                return null;
            
            return enumValues.Select(eVal => (int)eVal).ToList();
        }
    }
} 