/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class ServiceUsageReadonly : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? download1051200155;
        private double? upload364602541;
        private double? downloadLimit100000000000;
        private string periodStart;
        private string periodEnd;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("download `1051200155`")]
        public double? Download1051200155 
        { 
            get 
            {
                return this.download1051200155; 
            } 
            set 
            {
                this.download1051200155 = value;
                onPropertyChanged("Download1051200155");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("upload `364602541`")]
        public double? Upload364602541 
        { 
            get 
            {
                return this.upload364602541; 
            } 
            set 
            {
                this.upload364602541 = value;
                onPropertyChanged("Upload364602541");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("downloadLimit `100000000000`")]
        public double? DownloadLimit100000000000 
        { 
            get 
            {
                return this.downloadLimit100000000000; 
            } 
            set 
            {
                this.downloadLimit100000000000 = value;
                onPropertyChanged("DownloadLimit100000000000");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format
        /// </summary>
        [JsonProperty("periodStart")]
        public string PeriodStart 
        { 
            get 
            {
                return this.periodStart; 
            } 
            set 
            {
                this.periodStart = value;
                onPropertyChanged("PeriodStart");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format
        /// </summary>
        [JsonProperty("periodEnd")]
        public string PeriodEnd 
        { 
            get 
            {
                return this.periodEnd; 
            } 
            set 
            {
                this.periodEnd = value;
                onPropertyChanged("PeriodEnd");
            }
        }
    }
} 