/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class ServiceUpdate : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? servicePlanId;
        private double? servicePlanPeriodId;
        private string name;
        private double? price;
        private Models.InvoicingPeriodTypeEnum? invoicingPeriodType;
        private string invoiceLabel;
        private string activeTo;
        private double? nextInvoicingDayAdjustment;
        private bool? invoicingSeparately;
        private bool? sendEmailsAutomatically;
        private bool? useCreditAutomatically;
        private string contractId;
        private Models.ContractLengthTypeEnum? contractLengthType;
        private double? minimumContractLengthMonths;
        private string contractEndDate;
        private string street1;
        private string street2;
        private string city;
        private double? countryId;
        private double? stateId;
        private string zipCode;
        private double? addressGpsLat;
        private double? addressGpsLon;
        private string note;
        private string fccBlockId;

        /// <summary>
        /// See [Retrieve Service Plans](#reference/service-plans/service-plans/get)
        /// </summary>
        [JsonProperty("servicePlanId")]
        public double? ServicePlanId 
        { 
            get 
            {
                return this.servicePlanId; 
            } 
            set 
            {
                this.servicePlanId = value;
                onPropertyChanged("ServicePlanId");
            }
        }

        /// <summary>
        /// See [Retrieve Service Plan](#reference/service-plans/service-plansid/get)
        /// </summary>
        [JsonProperty("servicePlanPeriodId")]
        public double? ServicePlanPeriodId 
        { 
            get 
            {
                return this.servicePlanPeriodId; 
            } 
            set 
            {
                this.servicePlanPeriodId = value;
                onPropertyChanged("ServicePlanPeriodId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Changing this property only sets the individual price.
        /// </summary>
        [JsonProperty("price")]
        public double? Price 
        { 
            get 
            {
                return this.price; 
            } 
            set 
            {
                this.price = value;
                onPropertyChanged("Price");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("invoicingPeriodType")]
        public Models.InvoicingPeriodTypeEnum? InvoicingPeriodType 
        { 
            get 
            {
                return this.invoicingPeriodType; 
            } 
            set 
            {
                this.invoicingPeriodType = value;
                onPropertyChanged("InvoicingPeriodType");
            }
        }

        /// <summary>
        /// Individual invoice label to override default set in chosen service plan
        /// </summary>
        [JsonProperty("invoiceLabel")]
        public string InvoiceLabel 
        { 
            get 
            {
                return this.invoiceLabel; 
            } 
            set 
            {
                this.invoiceLabel = value;
                onPropertyChanged("InvoiceLabel");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format
        /// </summary>
        [JsonProperty("activeTo")]
        public string ActiveTo 
        { 
            get 
            {
                return this.activeTo; 
            } 
            set 
            {
                this.activeTo = value;
                onPropertyChanged("ActiveTo");
            }
        }

        /// <summary>
        /// Number of days to shift for before the default day, when the recurring invoices are automatically created
        /// </summary>
        [JsonProperty("nextInvoicingDayAdjustment")]
        public double? NextInvoicingDayAdjustment 
        { 
            get 
            {
                return this.nextInvoicingDayAdjustment; 
            } 
            set 
            {
                this.nextInvoicingDayAdjustment = value;
                onPropertyChanged("NextInvoicingDayAdjustment");
            }
        }

        /// <summary>
        /// Do not merge this service with other client's services into a single invoice
        /// </summary>
        [JsonProperty("invoicingSeparately")]
        public bool? InvoicingSeparately 
        { 
            get 
            {
                return this.invoicingSeparately; 
            } 
            set 
            {
                this.invoicingSeparately = value;
                onPropertyChanged("InvoicingSeparately");
            }
        }

        /// <summary>
        /// If `null`, system default is used
        /// Create and send the recurring invoice to client automatically. If not specified, taken from general settings
        /// </summary>
        [JsonProperty("sendEmailsAutomatically")]
        public bool? SendEmailsAutomatically 
        { 
            get 
            {
                return this.sendEmailsAutomatically; 
            } 
            set 
            {
                this.sendEmailsAutomatically = value;
                onPropertyChanged("SendEmailsAutomatically");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("useCreditAutomatically")]
        public bool? UseCreditAutomatically 
        { 
            get 
            {
                return this.useCreditAutomatically; 
            } 
            set 
            {
                this.useCreditAutomatically = value;
                onPropertyChanged("UseCreditAutomatically");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("contractId")]
        public string ContractId 
        { 
            get 
            {
                return this.contractId; 
            } 
            set 
            {
                this.contractId = value;
                onPropertyChanged("ContractId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("contractLengthType")]
        public Models.ContractLengthTypeEnum? ContractLengthType 
        { 
            get 
            {
                return this.contractLengthType; 
            } 
            set 
            {
                this.contractLengthType = value;
                onPropertyChanged("ContractLengthType");
            }
        }

        /// <summary>
        /// Minimum contract length in months
        /// </summary>
        [JsonProperty("minimumContractLengthMonths")]
        public double? MinimumContractLengthMonths 
        { 
            get 
            {
                return this.minimumContractLengthMonths; 
            } 
            set 
            {
                this.minimumContractLengthMonths = value;
                onPropertyChanged("MinimumContractLengthMonths");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format. Required in case of **Close end contract**
        /// </summary>
        [JsonProperty("contractEndDate")]
        public string ContractEndDate 
        { 
            get 
            {
                return this.contractEndDate; 
            } 
            set 
            {
                this.contractEndDate = value;
                onPropertyChanged("ContractEndDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("street1")]
        public string Street1 
        { 
            get 
            {
                return this.street1; 
            } 
            set 
            {
                this.street1 = value;
                onPropertyChanged("Street1");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("street2")]
        public string Street2 
        { 
            get 
            {
                return this.street2; 
            } 
            set 
            {
                this.street2 = value;
                onPropertyChanged("Street2");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("city")]
        public string City 
        { 
            get 
            {
                return this.city; 
            } 
            set 
            {
                this.city = value;
                onPropertyChanged("City");
            }
        }

        /// <summary>
        /// See [Retrieve Countries](#reference/general/countries/get)
        /// </summary>
        [JsonProperty("countryId")]
        public double? CountryId 
        { 
            get 
            {
                return this.countryId; 
            } 
            set 
            {
                this.countryId = value;
                onPropertyChanged("CountryId");
            }
        }

        /// <summary>
        /// Applicable in case of **United States** and **Canada** only.
        /// See [Retrieve States](#reference/general/countriesidstates/get)
        /// </summary>
        [JsonProperty("stateId")]
        public double? StateId 
        { 
            get 
            {
                return this.stateId; 
            } 
            set 
            {
                this.stateId = value;
                onPropertyChanged("StateId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("zipCode")]
        public string ZipCode 
        { 
            get 
            {
                return this.zipCode; 
            } 
            set 
            {
                this.zipCode = value;
                onPropertyChanged("ZipCode");
            }
        }

        /// <summary>
        /// Latitude of service location
        /// </summary>
        [JsonProperty("addressGpsLat")]
        public double? AddressGpsLat 
        { 
            get 
            {
                return this.addressGpsLat; 
            } 
            set 
            {
                this.addressGpsLat = value;
                onPropertyChanged("AddressGpsLat");
            }
        }

        /// <summary>
        /// Longitude of service location
        /// </summary>
        [JsonProperty("addressGpsLon")]
        public double? AddressGpsLon 
        { 
            get 
            {
                return this.addressGpsLon; 
            } 
            set 
            {
                this.addressGpsLon = value;
                onPropertyChanged("AddressGpsLon");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("note")]
        public string Note 
        { 
            get 
            {
                return this.note; 
            } 
            set 
            {
                this.note = value;
                onPropertyChanged("Note");
            }
        }

        /// <summary>
        /// Census block GEOID - used for FCC report generation
        /// </summary>
        [JsonProperty("fccBlockId")]
        public string FccBlockId 
        { 
            get 
            {
                return this.fccBlockId; 
            } 
            set 
            {
                this.fccBlockId = value;
                onPropertyChanged("FccBlockId");
            }
        }
    }
} 