/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class ServiceIp : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string ipRange;

        /// <summary>
        /// Supported formats: Single IP: 192.168.1.20, IP range: 192.168.1.20‑192.168.1.30 or 192.168.1.20‑30, IP range with netmask: 192.168.1.20/26
        /// </summary>
        [JsonProperty("ipRange")]
        public string IpRange 
        { 
            get 
            {
                return this.ipRange; 
            } 
            set 
            {
                this.ipRange = value;
                onPropertyChanged("IpRange");
            }
        }
    }
} 