/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class ServiceDevice : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double interfaceId;
        private double vendorId;
        private List<string> ipRange;
        private string macAddress;
        private string loginUsername;
        private string loginPassword;
        private double? sshPort;
        private bool? sendPingNotifications;
        private double? pingNotificationUserId;
        private bool? createPingStatistics;
        private bool? createSignalStatistics;
        private Models.QosEnabledEnum? qosEnabled = Models.QosEnabledEnum.ENUM_0;
        private List<double> qosDeviceIds;

        /// <summary>
        /// Device/router's interface to which the client's device is connected. This is important for suspend feature
        /// See [Retrieve Device Interfaces](#reference/device-interfaces/devicesiddevice-interfaces/get)
        /// </summary>
        [JsonProperty("interfaceId")]
        public double InterfaceId 
        { 
            get 
            {
                return this.interfaceId; 
            } 
            set 
            {
                this.interfaceId = value;
                onPropertyChanged("InterfaceId");
            }
        }

        /// <summary>
        /// See [Retrieve Vendors](#reference/vendors/vendors/get)
        /// </summary>
        [JsonProperty("vendorId")]
        public double VendorId 
        { 
            get 
            {
                return this.vendorId; 
            } 
            set 
            {
                this.vendorId = value;
                onPropertyChanged("VendorId");
            }
        }

        /// <summary>
        /// Supported formats: Single IP: 192.168.1.20, IP range: 192.168.1.20‑192.168.1.30 or 192.168.1.20‑30, IP range with netmask: 192.168.1.20/26
        /// </summary>
        [JsonProperty("ipRange")]
        public List<string> IpRange 
        { 
            get 
            {
                return this.ipRange; 
            } 
            set 
            {
                this.ipRange = value;
                onPropertyChanged("IpRange");
            }
        }

        /// <summary>
        /// Supported MAC formats are 00:AA:BB:00:11:22, 00‑AA‑BB‑00‑11‑22, 00AABB001122
        /// </summary>
        [JsonProperty("macAddress")]
        public string MacAddress 
        { 
            get 
            {
                return this.macAddress; 
            } 
            set 
            {
                this.macAddress = value;
                onPropertyChanged("MacAddress");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("loginUsername")]
        public string LoginUsername 
        { 
            get 
            {
                return this.loginUsername; 
            } 
            set 
            {
                this.loginUsername = value;
                onPropertyChanged("LoginUsername");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("loginPassword")]
        public string LoginPassword 
        { 
            get 
            {
                return this.loginPassword; 
            } 
            set 
            {
                this.loginPassword = value;
                onPropertyChanged("LoginPassword");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sshPort")]
        public double? SshPort 
        { 
            get 
            {
                return this.sshPort; 
            } 
            set 
            {
                this.sshPort = value;
                onPropertyChanged("SshPort");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sendPingNotifications")]
        public bool? SendPingNotifications 
        { 
            get 
            {
                return this.sendPingNotifications; 
            } 
            set 
            {
                this.sendPingNotifications = value;
                onPropertyChanged("SendPingNotifications");
            }
        }

        /// <summary>
        /// If not specified, default notification user will be used
        /// See [Retrieve Admins](#reference/users/usersadmins/get)
        /// </summary>
        [JsonProperty("pingNotificationUserId")]
        public double? PingNotificationUserId 
        { 
            get 
            {
                return this.pingNotificationUserId; 
            } 
            set 
            {
                this.pingNotificationUserId = value;
                onPropertyChanged("PingNotificationUserId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("createPingStatistics")]
        public bool? CreatePingStatistics 
        { 
            get 
            {
                return this.createPingStatistics; 
            } 
            set 
            {
                this.createPingStatistics = value;
                onPropertyChanged("CreatePingStatistics");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("createSignalStatistics")]
        public bool? CreateSignalStatistics 
        { 
            get 
            {
                return this.createSignalStatistics; 
            } 
            set 
            {
                this.createSignalStatistics = value;
                onPropertyChanged("CreateSignalStatistics");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("qosEnabled")]
        public Models.QosEnabledEnum? QosEnabled 
        { 
            get 
            {
                return this.qosEnabled; 
            } 
            set 
            {
                this.qosEnabled = value;
                onPropertyChanged("QosEnabled");
            }
        }

        /// <summary>
        /// Applicable in case of **On other device(s)** only
        /// See [Retrieve Devices](#reference/devices/devices/get)
        /// </summary>
        [JsonProperty("qosDeviceIds")]
        public List<double> QosDeviceIds 
        { 
            get 
            {
                return this.qosDeviceIds; 
            } 
            set 
            {
                this.qosDeviceIds = value;
                onPropertyChanged("QosDeviceIds");
            }
        }
    }
} 