/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class ServiceReadOnly : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? id;
        private double? clientId;
        private Models.ServiceStatusEnum? status;
        private bool? hasIndividualPrice;
        private double? totalPrice;
        private string servicePlanName;
        private double? servicePlanPrice;
        private double? servicePlanPeriod;
        private double? downloadSpeed;
        private double? uploadSpeed;
        private List<string> ipRanges;
        private string currencyCode;
        private bool? hasOutage;
        private string fccBlockId;
        private string lastInvoicedDate;
        private double? servicePlanId;
        private double? servicePlanPeriodId;
        private string activeFrom;
        private string activeTo;
        private string name;
        private double? price;
        private string note;
        private string invoicingStart;
        private Models.InvoicingPeriodTypeEnum? invoicingPeriodType;
        private double? invoicingPeriodStartDay;
        private double? nextInvoicingDayAdjustment;
        private bool? invoicingProratedSeparately;
        private bool? invoicingSeparately;
        private bool? sendEmailsAutomatically;
        private bool? useCreditAutomatically;
        private string invoiceLabel;
        private string street1;
        private string street2;
        private string city;
        private double? countryId;
        private double? stateId;
        private string zipCode;
        private double? addressGpsLat;
        private double? addressGpsLon;
        private string contractId;
        private Models.ContractLengthTypeEnum? contractLengthType = Models.ContractLengthTypeEnum.ENUM_1;
        private double? minimumContractLengthMonths;
        private string contractEndDate;
        private Models.DiscountTypeEnum? discountType = Models.DiscountTypeEnum.ENUM_0;
        private double? discountValue;
        private string discountInvoiceLabel;
        private string discountFrom;
        private string discountTo;
        private bool? taxable;
        private double? tax1Id;
        private double? tax2Id;
        private double? tax3Id;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public double? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("clientId")]
        public double? ClientId 
        { 
            get 
            {
                return this.clientId; 
            } 
            set 
            {
                this.clientId = value;
                onPropertyChanged("ClientId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("status")]
        public Models.ServiceStatusEnum? Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// True if the service price is set individually, false if it's inherited from service plan.
        /// </summary>
        [JsonProperty("hasIndividualPrice")]
        public bool? HasIndividualPrice 
        { 
            get 
            {
                return this.hasIndividualPrice; 
            } 
            set 
            {
                this.hasIndividualPrice = value;
                onPropertyChanged("HasIndividualPrice");
            }
        }

        /// <summary>
        /// Total price of service, including surcharges, discounts and taxes. Price is calculated for current invoicing period and thus accounts for time-limited discounts.
        /// </summary>
        [JsonProperty("totalPrice")]
        public double? TotalPrice 
        { 
            get 
            {
                return this.totalPrice; 
            } 
            set 
            {
                this.totalPrice = value;
                onPropertyChanged("TotalPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("servicePlanName")]
        public string ServicePlanName 
        { 
            get 
            {
                return this.servicePlanName; 
            } 
            set 
            {
                this.servicePlanName = value;
                onPropertyChanged("ServicePlanName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("servicePlanPrice")]
        public double? ServicePlanPrice 
        { 
            get 
            {
                return this.servicePlanPrice; 
            } 
            set 
            {
                this.servicePlanPrice = value;
                onPropertyChanged("ServicePlanPrice");
            }
        }

        /// <summary>
        /// Pricing period in months
        /// </summary>
        [JsonProperty("servicePlanPeriod")]
        public double? ServicePlanPeriod 
        { 
            get 
            {
                return this.servicePlanPeriod; 
            } 
            set 
            {
                this.servicePlanPeriod = value;
                onPropertyChanged("ServicePlanPeriod");
            }
        }

        /// <summary>
        /// Download speed in Mbps
        /// </summary>
        [JsonProperty("downloadSpeed")]
        public double? DownloadSpeed 
        { 
            get 
            {
                return this.downloadSpeed; 
            } 
            set 
            {
                this.downloadSpeed = value;
                onPropertyChanged("DownloadSpeed");
            }
        }

        /// <summary>
        /// Upload speed in Mbps
        /// </summary>
        [JsonProperty("uploadSpeed")]
        public double? UploadSpeed 
        { 
            get 
            {
                return this.uploadSpeed; 
            } 
            set 
            {
                this.uploadSpeed = value;
                onPropertyChanged("UploadSpeed");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ipRanges")]
        public List<string> IpRanges 
        { 
            get 
            {
                return this.ipRanges; 
            } 
            set 
            {
                this.ipRanges = value;
                onPropertyChanged("IpRanges");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("currencyCode")]
        public string CurrencyCode 
        { 
            get 
            {
                return this.currencyCode; 
            } 
            set 
            {
                this.currencyCode = value;
                onPropertyChanged("CurrencyCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("hasOutage")]
        public bool? HasOutage 
        { 
            get 
            {
                return this.hasOutage; 
            } 
            set 
            {
                this.hasOutage = value;
                onPropertyChanged("HasOutage");
            }
        }

        /// <summary>
        /// Census block GEOID - used for FCC report generation
        /// </summary>
        [JsonProperty("fccBlockId")]
        public string FccBlockId 
        { 
            get 
            {
                return this.fccBlockId; 
            } 
            set 
            {
                this.fccBlockId = value;
                onPropertyChanged("FccBlockId");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format or null if not yet invoiced.
        /// </summary>
        [JsonProperty("lastInvoicedDate")]
        public string LastInvoicedDate 
        { 
            get 
            {
                return this.lastInvoicedDate; 
            } 
            set 
            {
                this.lastInvoicedDate = value;
                onPropertyChanged("LastInvoicedDate");
            }
        }

        /// <summary>
        /// See [Retrieve Service Plans](#reference/service-plans/service-plans/get)
        /// </summary>
        [JsonProperty("servicePlanId")]
        public double? ServicePlanId 
        { 
            get 
            {
                return this.servicePlanId; 
            } 
            set 
            {
                this.servicePlanId = value;
                onPropertyChanged("ServicePlanId");
            }
        }

        /// <summary>
        /// See [Retrieve Service Plan](#reference/service-plans/service-plansid/get)
        /// </summary>
        [JsonProperty("servicePlanPeriodId")]
        public double? ServicePlanPeriodId 
        { 
            get 
            {
                return this.servicePlanPeriodId; 
            } 
            set 
            {
                this.servicePlanPeriodId = value;
                onPropertyChanged("ServicePlanPeriodId");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format. If not specified, current date will be used
        /// </summary>
        [JsonProperty("activeFrom")]
        public string ActiveFrom 
        { 
            get 
            {
                return this.activeFrom; 
            } 
            set 
            {
                this.activeFrom = value;
                onPropertyChanged("ActiveFrom");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format
        /// </summary>
        [JsonProperty("activeTo")]
        public string ActiveTo 
        { 
            get 
            {
                return this.activeTo; 
            } 
            set 
            {
                this.activeTo = value;
                onPropertyChanged("ActiveTo");
            }
        }

        /// <summary>
        /// If not specified, service plan name will be used
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Price from the chosen service plan period or the individual price if specified. Changing this property only sets the individual price.
        /// </summary>
        [JsonProperty("price")]
        public double? Price 
        { 
            get 
            {
                return this.price; 
            } 
            set 
            {
                this.price = value;
                onPropertyChanged("Price");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("note")]
        public string Note 
        { 
            get 
            {
                return this.note; 
            } 
            set 
            {
                this.note = value;
                onPropertyChanged("Note");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format. If not specified, current date will be used
        /// Service will be invoiced from this date including
        /// </summary>
        [JsonProperty("invoicingStart")]
        public string InvoicingStart 
        { 
            get 
            {
                return this.invoicingStart; 
            } 
            set 
            {
                this.invoicingStart = value;
                onPropertyChanged("InvoicingStart");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("invoicingPeriodType")]
        public Models.InvoicingPeriodTypeEnum? InvoicingPeriodType 
        { 
            get 
            {
                return this.invoicingPeriodType; 
            } 
            set 
            {
                this.invoicingPeriodType = value;
                onPropertyChanged("InvoicingPeriodType");
            }
        }

        /// <summary>
        /// Day in month when the recurring period starts. If not specified, current day will be used. Valid values are 1-28 and 31, where 31 means last day of month.
        /// </summary>
        [JsonProperty("invoicingPeriodStartDay")]
        public double? InvoicingPeriodStartDay 
        { 
            get 
            {
                return this.invoicingPeriodStartDay; 
            } 
            set 
            {
                this.invoicingPeriodStartDay = value;
                onPropertyChanged("InvoicingPeriodStartDay");
            }
        }

        /// <summary>
        /// Number of days to shift for before the default day, when the recurring invoices are automatically created
        /// </summary>
        [JsonProperty("nextInvoicingDayAdjustment")]
        public double? NextInvoicingDayAdjustment 
        { 
            get 
            {
                return this.nextInvoicingDayAdjustment; 
            } 
            set 
            {
                this.nextInvoicingDayAdjustment = value;
                onPropertyChanged("NextInvoicingDayAdjustment");
            }
        }

        /// <summary>
        /// Whether to invoice the first prorated period alone or together with the next whole period
        /// </summary>
        [JsonProperty("invoicingProratedSeparately")]
        public bool? InvoicingProratedSeparately 
        { 
            get 
            {
                return this.invoicingProratedSeparately; 
            } 
            set 
            {
                this.invoicingProratedSeparately = value;
                onPropertyChanged("InvoicingProratedSeparately");
            }
        }

        /// <summary>
        /// Do not merge this service with other client's services into a single invoice
        /// </summary>
        [JsonProperty("invoicingSeparately")]
        public bool? InvoicingSeparately 
        { 
            get 
            {
                return this.invoicingSeparately; 
            } 
            set 
            {
                this.invoicingSeparately = value;
                onPropertyChanged("InvoicingSeparately");
            }
        }

        /// <summary>
        /// If `null`, system default is used
        /// Create and send the recurring invoice to client automatically. If not specified, taken from general settings
        /// </summary>
        [JsonProperty("sendEmailsAutomatically")]
        public bool? SendEmailsAutomatically 
        { 
            get 
            {
                return this.sendEmailsAutomatically; 
            } 
            set 
            {
                this.sendEmailsAutomatically = value;
                onPropertyChanged("SendEmailsAutomatically");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("useCreditAutomatically")]
        public bool? UseCreditAutomatically 
        { 
            get 
            {
                return this.useCreditAutomatically; 
            } 
            set 
            {
                this.useCreditAutomatically = value;
                onPropertyChanged("UseCreditAutomatically");
            }
        }

        /// <summary>
        /// Individual invoice label to override default set in chosen service plan
        /// </summary>
        [JsonProperty("invoiceLabel")]
        public string InvoiceLabel 
        { 
            get 
            {
                return this.invoiceLabel; 
            } 
            set 
            {
                this.invoiceLabel = value;
                onPropertyChanged("InvoiceLabel");
            }
        }

        /// <summary>
        /// If not specified, taken from client
        /// </summary>
        [JsonProperty("street1")]
        public string Street1 
        { 
            get 
            {
                return this.street1; 
            } 
            set 
            {
                this.street1 = value;
                onPropertyChanged("Street1");
            }
        }

        /// <summary>
        /// If not specified, taken from client
        /// </summary>
        [JsonProperty("street2")]
        public string Street2 
        { 
            get 
            {
                return this.street2; 
            } 
            set 
            {
                this.street2 = value;
                onPropertyChanged("Street2");
            }
        }

        /// <summary>
        /// If not specified, taken from client
        /// </summary>
        [JsonProperty("city")]
        public string City 
        { 
            get 
            {
                return this.city; 
            } 
            set 
            {
                this.city = value;
                onPropertyChanged("City");
            }
        }

        /// <summary>
        /// If not specified, taken from client
        /// See [Retrieve Countries](#reference/general/countries/get)
        /// </summary>
        [JsonProperty("countryId")]
        public double? CountryId 
        { 
            get 
            {
                return this.countryId; 
            } 
            set 
            {
                this.countryId = value;
                onPropertyChanged("CountryId");
            }
        }

        /// <summary>
        /// Applicable in case of **United States** and **Canada** only. If not specified, taken from client
        /// See [Retrieve States](#reference/general/countriesidstates/get)
        /// </summary>
        [JsonProperty("stateId")]
        public double? StateId 
        { 
            get 
            {
                return this.stateId; 
            } 
            set 
            {
                this.stateId = value;
                onPropertyChanged("StateId");
            }
        }

        /// <summary>
        /// If not specified, taken from client
        /// </summary>
        [JsonProperty("zipCode")]
        public string ZipCode 
        { 
            get 
            {
                return this.zipCode; 
            } 
            set 
            {
                this.zipCode = value;
                onPropertyChanged("ZipCode");
            }
        }

        /// <summary>
        /// Latitude of service location
        /// </summary>
        [JsonProperty("addressGpsLat")]
        public double? AddressGpsLat 
        { 
            get 
            {
                return this.addressGpsLat; 
            } 
            set 
            {
                this.addressGpsLat = value;
                onPropertyChanged("AddressGpsLat");
            }
        }

        /// <summary>
        /// Longitude of service location
        /// </summary>
        [JsonProperty("addressGpsLon")]
        public double? AddressGpsLon 
        { 
            get 
            {
                return this.addressGpsLon; 
            } 
            set 
            {
                this.addressGpsLon = value;
                onPropertyChanged("AddressGpsLon");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("contractId")]
        public string ContractId 
        { 
            get 
            {
                return this.contractId; 
            } 
            set 
            {
                this.contractId = value;
                onPropertyChanged("ContractId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("contractLengthType")]
        public Models.ContractLengthTypeEnum? ContractLengthType 
        { 
            get 
            {
                return this.contractLengthType; 
            } 
            set 
            {
                this.contractLengthType = value;
                onPropertyChanged("ContractLengthType");
            }
        }

        /// <summary>
        /// Minimum contract length in months
        /// </summary>
        [JsonProperty("minimumContractLengthMonths")]
        public double? MinimumContractLengthMonths 
        { 
            get 
            {
                return this.minimumContractLengthMonths; 
            } 
            set 
            {
                this.minimumContractLengthMonths = value;
                onPropertyChanged("MinimumContractLengthMonths");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format. Required in case of **Close end contract**
        /// </summary>
        [JsonProperty("contractEndDate")]
        public string ContractEndDate 
        { 
            get 
            {
                return this.contractEndDate; 
            } 
            set 
            {
                this.contractEndDate = value;
                onPropertyChanged("ContractEndDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("discountType")]
        public Models.DiscountTypeEnum? DiscountType 
        { 
            get 
            {
                return this.discountType; 
            } 
            set 
            {
                this.discountType = value;
                onPropertyChanged("DiscountType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("discountValue")]
        public double? DiscountValue 
        { 
            get 
            {
                return this.discountValue; 
            } 
            set 
            {
                this.discountValue = value;
                onPropertyChanged("DiscountValue");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("discountInvoiceLabel")]
        public string DiscountInvoiceLabel 
        { 
            get 
            {
                return this.discountInvoiceLabel; 
            } 
            set 
            {
                this.discountInvoiceLabel = value;
                onPropertyChanged("DiscountInvoiceLabel");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format. Must match one of the selected service plan period's start dates
        /// </summary>
        [JsonProperty("discountFrom")]
        public string DiscountFrom 
        { 
            get 
            {
                return this.discountFrom; 
            } 
            set 
            {
                this.discountFrom = value;
                onPropertyChanged("DiscountFrom");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format. Must match one of the selected service plan period's end dates
        /// </summary>
        [JsonProperty("discountTo")]
        public string DiscountTo 
        { 
            get 
            {
                return this.discountTo; 
            } 
            set 
            {
                this.discountTo = value;
                onPropertyChanged("DiscountTo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("taxable")]
        public bool? Taxable 
        { 
            get 
            {
                return this.taxable; 
            } 
            set 
            {
                this.taxable = value;
                onPropertyChanged("Taxable");
            }
        }

        /// <summary>
        /// Applicable if the service is taxable. If not specified, taken from client
        /// See [Retrieve Taxes](#reference/taxes/taxes/get)
        /// </summary>
        [JsonProperty("tax1Id")]
        public double? Tax1Id 
        { 
            get 
            {
                return this.tax1Id; 
            } 
            set 
            {
                this.tax1Id = value;
                onPropertyChanged("Tax1Id");
            }
        }

        /// <summary>
        /// Applicable if the service is taxable. If not specified, taken from client
        /// See [Retrieve Taxes](#reference/taxes/taxes/get)
        /// </summary>
        [JsonProperty("tax2Id")]
        public double? Tax2Id 
        { 
            get 
            {
                return this.tax2Id; 
            } 
            set 
            {
                this.tax2Id = value;
                onPropertyChanged("Tax2Id");
            }
        }

        /// <summary>
        /// Applicable if the service is taxable. If not specified, taken from client
        /// See [Retrieve Taxes](#reference/taxes/taxes/get)
        /// </summary>
        [JsonProperty("tax3Id")]
        public double? Tax3Id 
        { 
            get 
            {
                return this.tax3Id; 
            } 
            set 
            {
                this.tax3Id = value;
                onPropertyChanged("Tax3Id");
            }
        }
    }
} 