/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class Site : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string name;
        private string address;
        private string gpsLat;
        private string gpsLon;
        private string contactInfo;
        private string notes;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("address")]
        public string Address 
        { 
            get 
            {
                return this.address; 
            } 
            set 
            {
                this.address = value;
                onPropertyChanged("Address");
            }
        }

        /// <summary>
        /// Latitude of site location
        /// </summary>
        [JsonProperty("gpsLat")]
        public string GpsLat 
        { 
            get 
            {
                return this.gpsLat; 
            } 
            set 
            {
                this.gpsLat = value;
                onPropertyChanged("GpsLat");
            }
        }

        /// <summary>
        /// Longitude of site location
        /// </summary>
        [JsonProperty("gpsLon")]
        public string GpsLon 
        { 
            get 
            {
                return this.gpsLon; 
            } 
            set 
            {
                this.gpsLon = value;
                onPropertyChanged("GpsLon");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("contactInfo")]
        public string ContactInfo 
        { 
            get 
            {
                return this.contactInfo; 
            } 
            set 
            {
                this.contactInfo = value;
                onPropertyChanged("ContactInfo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("notes")]
        public string Notes 
        { 
            get 
            {
                return this.notes; 
            } 
            set 
            {
                this.notes = value;
                onPropertyChanged("Notes");
            }
        }
    }
} 