/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class Tariff : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string name;
        private double? organizationId;
        private string invoiceLabel;
        private double? downloadBurst;
        private double? uploadBurst;
        private double? downloadSpeed;
        private double? uploadSpeed;
        private double? dataUsageLimit;
        private bool? taxable;
        private List<Models.TariffPeriod> periods;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// If not specified, default organization will be used
        /// </summary>
        [JsonProperty("organizationId")]
        public double? OrganizationId 
        { 
            get 
            {
                return this.organizationId; 
            } 
            set 
            {
                this.organizationId = value;
                onPropertyChanged("OrganizationId");
            }
        }

        /// <summary>
        /// If not specified, name will be used
        /// </summary>
        [JsonProperty("invoiceLabel")]
        public string InvoiceLabel 
        { 
            get 
            {
                return this.invoiceLabel; 
            } 
            set 
            {
                this.invoiceLabel = value;
                onPropertyChanged("InvoiceLabel");
            }
        }

        /// <summary>
        /// Download burst in kB
        /// </summary>
        [JsonProperty("downloadBurst")]
        public double? DownloadBurst 
        { 
            get 
            {
                return this.downloadBurst; 
            } 
            set 
            {
                this.downloadBurst = value;
                onPropertyChanged("DownloadBurst");
            }
        }

        /// <summary>
        /// Upload burst in kB
        /// </summary>
        [JsonProperty("uploadBurst")]
        public double? UploadBurst 
        { 
            get 
            {
                return this.uploadBurst; 
            } 
            set 
            {
                this.uploadBurst = value;
                onPropertyChanged("UploadBurst");
            }
        }

        /// <summary>
        /// Download speed in Mbps
        /// </summary>
        [JsonProperty("downloadSpeed")]
        public double? DownloadSpeed 
        { 
            get 
            {
                return this.downloadSpeed; 
            } 
            set 
            {
                this.downloadSpeed = value;
                onPropertyChanged("DownloadSpeed");
            }
        }

        /// <summary>
        /// Upload speed in Mbps
        /// </summary>
        [JsonProperty("uploadSpeed")]
        public double? UploadSpeed 
        { 
            get 
            {
                return this.uploadSpeed; 
            } 
            set 
            {
                this.uploadSpeed = value;
                onPropertyChanged("UploadSpeed");
            }
        }

        /// <summary>
        /// Data usage limit in GB
        /// </summary>
        [JsonProperty("dataUsageLimit")]
        public double? DataUsageLimit 
        { 
            get 
            {
                return this.dataUsageLimit; 
            } 
            set 
            {
                this.dataUsageLimit = value;
                onPropertyChanged("DataUsageLimit");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("taxable")]
        public bool? Taxable 
        { 
            get 
            {
                return this.taxable; 
            } 
            set 
            {
                this.taxable = value;
                onPropertyChanged("Taxable");
            }
        }

        /// <summary>
        /// By default 1 month period is enabled
        /// </summary>
        [JsonProperty("periods")]
        public List<Models.TariffPeriod> Periods 
        { 
            get 
            {
                return this.periods; 
            } 
            set 
            {
                this.periods = value;
                onPropertyChanged("Periods");
            }
        }
    }
} 