/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class TaxReadOnly : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? id;
        private bool? selected;
        private string name;
        private string agencyName;
        private double? rate;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public double? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// Is selected to be assigned to every new client as default
        /// </summary>
        [JsonProperty("selected")]
        public bool? Selected 
        { 
            get 
            {
                return this.selected; 
            } 
            set 
            {
                this.selected = value;
                onPropertyChanged("Selected");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("agencyName")]
        public string AgencyName 
        { 
            get 
            {
                return this.agencyName; 
            } 
            set 
            {
                this.agencyName = value;
                onPropertyChanged("AgencyName");
            }
        }

        /// <summary>
        /// Tax rate in percentage
        /// </summary>
        [JsonProperty("rate")]
        public double? Rate 
        { 
            get 
            {
                return this.rate; 
            } 
            set 
            {
                this.rate = value;
                onPropertyChanged("Rate");
            }
        }
    }
} 