/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class TicketCommentAttachmentReadOnly : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? id;
        private double? size;
        private string mimeType;
        private string filename;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public double? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// Size of file in bytes
        /// </summary>
        [JsonProperty("size")]
        public double? Size 
        { 
            get 
            {
                return this.size; 
            } 
            set 
            {
                this.size = value;
                onPropertyChanged("Size");
            }
        }

        /// <summary>
        /// MIME Type of file
        /// </summary>
        [JsonProperty("mimeType")]
        public string MimeType 
        { 
            get 
            {
                return this.mimeType; 
            } 
            set 
            {
                this.mimeType = value;
                onPropertyChanged("MimeType");
            }
        }

        /// <summary>
        /// File name
        /// </summary>
        [JsonProperty("filename")]
        public string Filename 
        { 
            get 
            {
                return this.filename; 
            } 
            set 
            {
                this.filename = value;
                onPropertyChanged("Filename");
            }
        }
    }
} 