/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class TicketActivityClientAssignment : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? assignedClientId;

        /// <summary>
        /// See [Retrieve Clients](#reference/clients/clients/get)
        /// </summary>
        [JsonProperty("assignedClientId")]
        public double? AssignedClientId 
        { 
            get 
            {
                return this.assignedClientId; 
            } 
            set 
            {
                this.assignedClientId = value;
                onPropertyChanged("AssignedClientId");
            }
        }
    }
} 