/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;



namespace webapi.Models
{
    public enum TicketStatusEnum
    {
        ENUM_0 = 0, //New
        ENUM_1 = 1, //Open
        ENUM_2 = 2, //Pending
        ENUM_3 = 3, //Solved
    }

    /// <summary>
    /// Helper for the enum type TicketStatusEnum
    /// </summary>
    public static class TicketStatusEnumHelper
    {
        /// <summary>
        /// Convert a list of TicketStatusEnum values to a list of integers
        /// </summary>
        /// <param name="enumValues">The list of TicketStatusEnum values to convert</param>
        /// <returns>The list of representative integer values</returns>
        public static List<int> ToValue(List<TicketStatusEnum> enumValues)
        {
            if (null == enumValues)
                return null;
            
            return enumValues.Select(eVal => (int)eVal).ToList();
        }
    }
} 