/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class TicketReadOnly : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? id;
        private string lastActivity;
        private string lastCommentAt;
        private string isLastActivityByClient;
        private List<Models.TicketActivityReadOnly> activity;
        private string subject;
        private double? clientId;
        private string emailFromAddress;
        private string emailFromName;
        private double? assignedGroupId;
        private double? assignedUserId;
        private string createdAt;
        private Models.TicketStatusEnum? status;
        private bool? mpublic;
        private List<double> assignedJobIds;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public double? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format.
        /// </summary>
        [JsonProperty("lastActivity")]
        public string LastActivity 
        { 
            get 
            {
                return this.lastActivity; 
            } 
            set 
            {
                this.lastActivity = value;
                onPropertyChanged("LastActivity");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format.
        /// </summary>
        [JsonProperty("lastCommentAt")]
        public string LastCommentAt 
        { 
            get 
            {
                return this.lastCommentAt; 
            } 
            set 
            {
                this.lastCommentAt = value;
                onPropertyChanged("LastCommentAt");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format.
        /// </summary>
        [JsonProperty("isLastActivityByClient")]
        public string IsLastActivityByClient 
        { 
            get 
            {
                return this.isLastActivityByClient; 
            } 
            set 
            {
                this.isLastActivityByClient = value;
                onPropertyChanged("IsLastActivityByClient");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("activity")]
        public List<Models.TicketActivityReadOnly> Activity 
        { 
            get 
            {
                return this.activity; 
            } 
            set 
            {
                this.activity = value;
                onPropertyChanged("Activity");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("subject")]
        public string Subject 
        { 
            get 
            {
                return this.subject; 
            } 
            set 
            {
                this.subject = value;
                onPropertyChanged("Subject");
            }
        }

        /// <summary>
        /// If not set, `emailFromAddress` is required.
        /// See [Retrieve Clients](#reference/clients/clients/get)
        /// </summary>
        [JsonProperty("clientId")]
        public double? ClientId 
        { 
            get 
            {
                return this.clientId; 
            } 
            set 
            {
                this.clientId = value;
                onPropertyChanged("ClientId");
            }
        }

        /// <summary>
        /// When set, the ticket behaves as if imported by IMAP integration.
        /// </summary>
        [JsonProperty("emailFromAddress")]
        public string EmailFromAddress 
        { 
            get 
            {
                return this.emailFromAddress; 
            } 
            set 
            {
                this.emailFromAddress = value;
                onPropertyChanged("EmailFromAddress");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("emailFromName")]
        public string EmailFromName 
        { 
            get 
            {
                return this.emailFromName; 
            } 
            set 
            {
                this.emailFromName = value;
                onPropertyChanged("EmailFromName");
            }
        }

        /// <summary>
        /// See [Retrieve TicketGroups](#reference/ticket-groups/ticketingticket-groups/get)
        /// </summary>
        [JsonProperty("assignedGroupId")]
        public double? AssignedGroupId 
        { 
            get 
            {
                return this.assignedGroupId; 
            } 
            set 
            {
                this.assignedGroupId = value;
                onPropertyChanged("AssignedGroupId");
            }
        }

        /// <summary>
        /// See [Retrieve Users](#reference/users/usersadmins/get)
        /// </summary>
        [JsonProperty("assignedUserId")]
        public double? AssignedUserId 
        { 
            get 
            {
                return this.assignedUserId; 
            } 
            set 
            {
                this.assignedUserId = value;
                onPropertyChanged("AssignedUserId");
            }
        }

        /// <summary>
        /// Date string in ISO 8601 format. If not specified, current date will be used
        /// </summary>
        [JsonProperty("createdAt")]
        public string CreatedAt 
        { 
            get 
            {
                return this.createdAt; 
            } 
            set 
            {
                this.createdAt = value;
                onPropertyChanged("CreatedAt");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("status")]
        public Models.TicketStatusEnum? Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// Is visible to client?
        /// </summary>
        [JsonProperty("public")]
        public bool? Public 
        { 
            get 
            {
                return this.mpublic; 
            } 
            set 
            {
                this.mpublic = value;
                onPropertyChanged("Public");
            }
        }

        /// <summary>
        /// See [Retrieve Jobs](#reference/jobs/schedulingjobsclientidassigneduseriddatefromdateto/get)
        /// </summary>
        [JsonProperty("assignedJobIds")]
        public List<double> AssignedJobIds 
        { 
            get 
            {
                return this.assignedJobIds; 
            } 
            set 
            {
                this.assignedJobIds = value;
                onPropertyChanged("AssignedJobIds");
            }
        }
    }
} 