/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class TicketActivityCommentWritable : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string body;
        private List<Models.TicketCommentAttachmentWritable> attachments;
        private string emailFromAddress;
        private string emailFromName;

        /// <summary>
        /// Required when **attachments** is not specified.
        /// </summary>
        [JsonProperty("body")]
        public string Body 
        { 
            get 
            {
                return this.body; 
            } 
            set 
            {
                this.body = value;
                onPropertyChanged("Body");
            }
        }

        /// <summary>
        /// Required when **body** is not specified.
        /// </summary>
        [JsonProperty("attachments")]
        public List<Models.TicketCommentAttachmentWritable> Attachments 
        { 
            get 
            {
                return this.attachments; 
            } 
            set 
            {
                this.attachments = value;
                onPropertyChanged("Attachments");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("emailFromAddress")]
        public string EmailFromAddress 
        { 
            get 
            {
                return this.emailFromAddress; 
            } 
            set 
            {
                this.emailFromAddress = value;
                onPropertyChanged("EmailFromAddress");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("emailFromName")]
        public string EmailFromName 
        { 
            get 
            {
                return this.emailFromName; 
            } 
            set 
            {
                this.emailFromName = value;
                onPropertyChanged("EmailFromName");
            }
        }
    }
} 