/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class TotalTax : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string name;
        private double? totalValue;

        /// <summary>
        /// Name and rate of tax
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Sum of all taxes of this kind.
        /// </summary>
        [JsonProperty("totalValue")]
        public double? TotalValue 
        { 
            get 
            {
                return this.totalValue; 
            } 
            set 
            {
                this.totalValue = value;
                onPropertyChanged("TotalValue");
            }
        }
    }
} 