/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class TrafficItem : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string date;
        private double? upload;
        private double? download;

        /// <summary>
        /// Format `YYYY-MM-DD`.
        /// </summary>
        [JsonProperty("date")]
        public string Date 
        { 
            get 
            {
                return this.date; 
            } 
            set 
            {
                this.date = value;
                onPropertyChanged("Date");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("upload")]
        public double? Upload 
        { 
            get 
            {
                return this.upload; 
            } 
            set 
            {
                this.upload = value;
                onPropertyChanged("Upload");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("download")]
        public double? Download 
        { 
            get 
            {
                return this.download; 
            } 
            set 
            {
                this.download = value;
                onPropertyChanged("Download");
            }
        }
    }
} 