/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;



namespace webapi.Models
{
    public enum TypeEnum
    {
        ENUM_1 = 1, //Invoice
        ENUM_2 = 2, //Payment
        ENUM_3 = 3, //Refund
    }

    /// <summary>
    /// Helper for the enum type TypeEnum
    /// </summary>
    public static class TypeEnumHelper
    {
        /// <summary>
        /// Convert a list of TypeEnum values to a list of integers
        /// </summary>
        /// <param name="enumValues">The list of TypeEnum values to convert</param>
        /// <returns>The list of representative integer values</returns>
        public static List<int> ToValue(List<TypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;
            
            return enumValues.Select(eVal => (int)eVal).ToList();
        }
    }
} 