/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;



namespace webapi.Models
{
    public enum Type1Enum
    {
        ENUM_0 = 0, //Unknown
        ENUM_1 = 1, //Wireless
        ENUM_2 = 2, //Ethernet
        ENUM_3 = 3, //Vlan
        ENUM_4 = 4, //Mesh
        ENUM_5 = 5, //Bonding
        ENUM_6 = 6, //Bridge
        ENUM_7 = 7, //CAP
        ENUM_8 = 8, //GRE
        ENUM_9 = 9, //GRE6
        ENUM_10 = 10, //L2TP
        ENUM_11 = 11, //OVPN
        ENUM_12 = 12, //PPPoE
        ENUM_13 = 13, //PPTP
        ENUM_14 = 14, //SSTP
        ENUM_15 = 15, //VPLS
        ENUM_16 = 16, //Traffic eng
        ENUM_17 = 17, //VRRP
        ENUM_18 = 18, //WDS
    }

    /// <summary>
    /// Helper for the enum type Type1Enum
    /// </summary>
    public static class Type1EnumHelper
    {
        /// <summary>
        /// Convert a list of Type1Enum values to a list of integers
        /// </summary>
        /// <param name="enumValues">The list of Type1Enum values to convert</param>
        /// <returns>The list of representative integer values</returns>
        public static List<int> ToValue(List<Type1Enum> enumValues)
        {
            if (null == enumValues)
                return null;
            
            return enumValues.Select(eVal => (int)eVal).ToList();
        }
    }
} 