/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;



namespace webapi.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum Type3Enum
    {
        COMMENT, //TODO: Write general description for this method
        ASSIGNMENT, //TODO: Write general description for this method
        ASSIGNMENT_CLIENT, //TODO: Write general description for this method
        ASSIGNMENT_JOB, //TODO: Write general description for this method
        STATUS_CHANGE, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type Type3Enum
    /// </summary>
    public static class Type3EnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "comment", "assignment", "assignment_client", "assignment_job", "status_change" };

        /// <summary>
        /// Converts a Type3Enum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The Type3Enum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(Type3Enum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case Type3Enum.COMMENT:
                case Type3Enum.ASSIGNMENT:
                case Type3Enum.ASSIGNMENT_CLIENT:
                case Type3Enum.ASSIGNMENT_JOB:
                case Type3Enum.STATUS_CHANGE:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of Type3Enum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of Type3Enum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<Type3Enum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into Type3Enum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed Type3Enum value</returns>
        public static Type3Enum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type Type3Enum", value));

            return (Type3Enum) index;
        }
    }
} 