/*
 * UCRMAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;




namespace webapi.Models
{
    public class WebhookEvent : BaseModel 
    {
        // These fields hold the values for the public properties.
        public string uuid { get; set; }
        public string changeType { get; set; }
        public string entity { get; set; }
        public double? entityId { get; set; }
        public string eventName { get; set; }
    }
    public class WebhookEventInvoice 
    {
        // These fields hold the values for the public properties.
        public string uuid { get; set; }
        public string changeType { get; set; }
        public string entity { get; set; }
        public double? entityId { get; set; }
        public string eventName { get; set; }
        public extradatainvoice extraData { get; set; }

    }
    public class extradatainvoice
    {
        public InvoiceReadOnly entity { get; set; } 
    }
    public class WebhookEventPayment
    {
        // These fields hold the values for the public properties.
        public string uuid { get; set; }
        public string changeType { get; set; }
        public string entity { get; set; }
        public double? entityId { get; set; }
        public string eventName { get; set; }
        public extradatapayment extraData { get; set; }

    }
    public class extradatapayment
    {
        public PaymentReadOnly entity { get; set; }
    }
    public class WebhookEventClient
    {
        // These fields hold the values for the public properties.
        public string uuid { get; set; }
        public string changeType { get; set; }
        public string entity { get; set; }
        public double? entityId { get; set; }
        public string eventName { get; set; }
        public extradataclient extraData { get; set; }

    }
    public class extradataclient
    {
        public ClientReadOnly entity { get; set; }
    }
    public class WebhookEventTicket
    {
        // These fields hold the values for the public properties.
        public string uuid { get; set; }
        public string changeType { get; set; }
        public string entity { get; set; }
        public double? entityId { get; set; }
        public string eventName { get; set; }
        public extradataticket extraData { get; set; }

    }
    public class extradataticket
    {
        public TicketReadOnly entity { get; set; }
    }
    public class WebhookEventService
    {
        // These fields hold the values for the public properties.
        public string uuid { get; set; }
        public string changeType { get; set; }
        public string entity { get; set; }
        public double? entityId { get; set; }
        public string eventName { get; set; }
        public extradataservice extraData { get; set; }

    }
    public class extradataservice
    {
        public ServiceReadOnly entity { get; set; }
    }

} 